name: Continuous Integration

on:
  pull_request:
  push:

jobs:
  check-linting-and-formatting:
    runs-on: ubuntu-latest
    container: jamieleecho/coco-dev:latest
    options: --user root
    steps:
      - uses: actions/checkout@master

      - name: Check linting, formatting
        run: |
          make check-all

  check-build:
    runs-on: ubuntu-latest
    container: jamieleecho/coco-dev:latest
    options: --user root
    steps:
      - uses: actions/checkout@master

      - name: Install Requirements
        run: |
          make sync

      - name: Run tests
        run: |
          make run-tests

      - name: Check compile
        run: |
          make
